### ISSUE TITLE
Unable to resolve type in nodeDefinitions

### ISSUE THREAD

**Issue by Nutelac** [graphql/graphql-relay-js#14]
I'm fetching data from MySQL database, but I'm unable to resolve types of returned data by `instanceof` operator or by it's content (they are just pure JS objects, they don't have any specific class). My `nodeDefinitions` looks something like that:
```javascript
let {nodeInterface, nodeField} = nodeDefinitions(
  (globalId) => {
    let {type, id} = fromGlobalId(globalId)
    return db.findOne(type, id)
  },
  (obj) => {
    // can't resolve type of obj
  }
)
```

What is the prefered way to solve this problem? So far I invented just this, but it's ugly because it change returned object:
```javascript
let {nodeInterface, nodeField} = nodeDefinitions(
  (globalId) => {
    let {type, id} = fromGlobalId(globalId)
    return Object.assign({_type: type}, db.findOne(type, id))
  },
  (obj) => {
    if(obj._type === 'User') {
      return userType
    } else if(obj._type === 'Article') {
      return articleType
    }
    // ... and so on
  }
)
```

Can you think of any better solution? Thank you.

**Comment by dschafer** [comment]
Yeah, this is tricky. An option might be

```js
let {nodeInterface, nodeField} = nodeDefinitions(
  (globalId) => {
    let {type, id} = fromGlobalId(globalId)
    return Object.assign({globalId}, db.findOne(type, id))
  },
  (obj) => {
    let {type} = fromGlobalId(obj.globalId);
    if(type === 'User') {
      return userType
    } else if(type === 'Article') {
      return articleType
    }
    // ... and so on
  }
)
```

and then you can just have the `id` field on these objects return `globalId`. But the larger problem is that anytime you have a field that returns `Node` (or any other interface), GraphQL needs to be able to map from the resolved value to the concrete type. So I could see having a helper method:

```js
function dbFindOneWithType(type, id) {
   return Object.assign({_type: type}, db.findOne(type, id))
}
```

and then use that in place of `db.findOne` for all fetches, so that the objects are always tagged with their types.

Let me know if this helps, or if there are API changes that you think would make this easier!

**Comment by dschafer** [comment]
Feel free to re-open if you're still having issues.
