### ISSUE TITLE
Return cursor on mutation's payload issue

### ISSUE THREAD

**Issue by dclarke-modus** [graphql/graphql-relay-js#206]
Good day:

I have a use case that might not be covered with GraphQL architecture or I maybe using it incorrectly. So I have 2 steps in a Relay process:

1. Fetch a list of records for my Paginated Container with a filter {name: 'blah'}. This essentially would be a sub-list of the bigger list depending on the filter. So say the total record in the DB is 100 but, with the filter, you only return 20 records, the cursor would be based on 20 records.

2. Subsequently I send a create record mutation and I want to get the cursor (so I can add the record to my Paginated Connection on the client). My mutation payload would need the cursor in this case and if I had to generate it with say offsetToCursor.

```
 mutation scopeMutation($input: ScopeMutationInput!) {

  createScope(input:$input) {
        node {  
            id
            enabled
            name
            description
            grants
            createdAt
       }
       cursor
   }
}
```

I do not know what the original filter (from step #1 is). So essentially I'd have to do offsetToCursor(collection.find({}).length), which would be wrong because, this would return 101 and not 21.

**Comment by benjie** [comment]
The cursor shouldn't really be based on an offset because that would be invalidated if a new record is inserted at the beginning of the set. The cursor should point to one element within an "ordered" list; so for example if I had this table:

id | a | b | c
=== | === | === | ===
995 | 2 | 1 | 'cat'
996 | 1 | 1 | 'dog'
997 | 3 | 2 | 'fish'
998 | 4 | 1 | 'dog'

If I order by "b asc, a asc" then I might use the following cursors (note the table has been reordered):

id | a | b | c | cursor(order: b asc, a asc)
=== | === | === | === | ===
996 | 1 | 1 | 'dog' | '1,1,996'
995 | 2 | 1 | 'cat' | '1,2,995'
998 | 4 | 1 | 'dog' | '1,4,998'
997 | 3 | 2 | 'fish' | '2,3,997'

Now if I insert a new record at the front:

id | a | b | c | cursor(order: b asc, a asc)
=== | === | === | === | ===
1010 | 0 | 0 | 'ant' | '0,0,1010'
996 | 1 | 1 | 'dog' | '1,1,996'
995 | 2 | 1 | 'cat' | '1,2,995'
998 | 4 | 1 | 'dog' | '1,4,998'
997 | 3 | 2 | 'fish' | '2,3,997'

the other cursors have not changed; and by using the cursor I can tell my database to only show things "before" or "after" any record that I have a cursor for.

[PostGraphile](https://www.graphile.org/postgraphile/) solves this on mutations by making a `scopeEdge` field available on the payload that has an "orderBy" argument so that we can return the cursor for that newly created record when ordered according to the given criteria - this is independent of other records in the database.
