### ISSUE TITLE
What is the use case for returning the cursor of each individual node?

### ISSUE THREAD

**Issue by luisobo** [graphql/graphql-relay-js#27]
Hi,

I was wondering what is the use case for returning the cursor along with every node in a connection. Given that `pageInfo` has the start and end cursor, that would suffice for pagination purposes as far as I understand.

The reason I'm asking is because there is too much indirection in the schema (and therefore, in the queries) when retrieving fields from a connection:

```
{
  articles {
   pageInfo { ... }
    edges {
      node {
        title
      }
    }
  }
}
```

Ideally this could be:

```
{
  articles {
   pageInfo { ... }
    nodes {
      title
    }
  }
}
```

which removes one level of indirection.

Thanks for your time.

**Comment by dschafer** [comment]
CC @yuzhi who can describe what the Relay store does with the cursors on each edge, and hence why it uses `edges` rather than `nodes`.

Internally, we expose `nodes` for exactly the reason you describe: if you don't need edge data or the cursor, it's quite convenient to skip straight to the nodes; that's definitely a useful pattern.

**Comment by luisobo** [comment]
Yeah, that's what @leebyron suggested on facebook/graphql#4. 

Can't what to hear the purpose of that. I'm guessing something related to nodes being evicted out of a local cache and refetching parts of a connection?

**Comment by yuzhi** [comment]
We fetch cursors on every edge so that if you have a component that asks for `first:10` and have it cached and later another component asks for `first:5`, we can generated the correct pageInfo based on the cursors we have fetched from `first:10` for `first:5` without doing a server round trip.
Another case is, if some of the edges are deleted through mutations, we still have the cursors form the other edges to fetch for additional edges.

**Comment by luisobo** [comment]
Interesting thanks!

/cc @modocache @akatz

**Comment by dschafer** [comment]
Note that while Relay requires `edges` for its pagination, it doesn't have an opinion on whether `nodes` is exposed. So if you find `nodes` convenient for browsing APIs (I certainly do), I'd definitely add it in! If you do so, Relay has a check in place so that if you query for `nodes` instead of `edges`, it will warn and suggest querying for `edges` instead.
