### ISSUE TITLE
PageInfo Incorrect for Dynamically Retrieved Arrays

### ISSUE THREAD

**Issue by darthtrevino** [graphql/graphql-relay-js#64]
My resolve function retrieves data from a database using the standard `first` argument as a limit.
```js
resolve(_, args) =>  {
   criteria = makeCriteriaFromArguments(args);
   criteria.limit = args.first;
   const result = stuffRepository.findAll(criteria);
   return connectionFromPromisedArray(result, args);
};
```

In this case, when `connectionFromPromisedArray` thunks over to `connectionFromArraySlice`, the end offset and the upperbound will be equal (https://github.com/graphql/graphql-relay-js/blob/master/src/connection/arrayconnection.js#L121).  The resultant **PageInfo**, emitted by `connectionFromPromisedArray` would have 
```js
{ hasNextPage: false, ... } 
```

For this use case, I would expect this:
```js
hasNextPage: first != null ? endOffset <= upperBound : false,
```
instead of 
```
hasNextPage: first != null ? endOffset < upperBound : false,
```

I could resolve this by overfetching my collection by one, but that would be really hacky.

**Comment by darthtrevino** [comment]
So it looks like the array slicing logic assumes that it's dealing with an entire set of data and paginates based on the incoming args. This may work fine for a fistful of entities, but when there can be a million connections, it's an unsuitable solution. 

I'll do my own edge conversion for the time being, but it would be nice if this library supported true dynamic paging without slurping an entire connection array into memory.

**Comment by wincent** [comment]
Thanks for bringing this up.

> So it looks like the array slicing logic assumes that it's dealing with an entire set of data and paginates based on the incoming args. This may work fine for a fistful of entities, but when there can be a million connections, it's an unsuitable solution.

The entire point of the `ArraySlice` methods is [to avoid dealing with the entire set](https://github.com/graphql/graphql-relay-js/blob/deb4f5ee145fe2cae0ad90d8f584b6d0089eff25/src/connection/arrayconnection.js#L61-L64):

```
/**
 * Given a slice (subset) of an array, returns a connection object for use in
 * GraphQL.
 *
 * This function is similar to `connectionFromArray`, but is intended for use
 * cases where you know the cardinality of the connection, consider it too large
 * to materialize the entire array, and instead wish pass in a slice of the
 * total result large enough to cover the range specified in `args`.
 */
```

So, I would think that if you used `connectionFromPromisedArraySlice` (instead of `connectionFromPromisedArray`), you should be able to get what you want. Is this not the case?

> I could resolve this by overfetching my collection by one, but that would be really hacky.

It's been a while since I looked at this code but it's possible that there's a bug in there, especially because I'm the one that added the `ArraySlice` stuff. There are some confusing edge-casey aspects to the connection spec, so I tried to follow it to the letter and keep all existing tests passing, but it is possible that I made a mistake (for more context, see the original commit message in 238d724a6c14).

**Comment by darthtrevino** [comment]
I see, I should have read the headers more closely. Thanks for clearing that up @wincent !

**Comment by wincent** [comment]
No problem!
