### ISSUE TITLE
Does relay support pagination when the size of the collection is unknown?

### ISSUE THREAD

**Issue by jnak** [graphql/graphql-relay-js#82]
Does relay support pagination when the size of the collection is unknown? ie sometimes it is expensive to know the exact size of a collection or just needed from a product perspective. Like search results.

While I understand you need the exact size to support the 'last' argument if 'before' or 'first', what's the most relay-compliant way to support those cases? Maybe the answer is to not worry about it (pick an arbitrary long size) and make sure relay never emits a 'last' query on that connection. Any thoughts?

On a related note, any best practice on how to handle a non-static collection? like a facebook feed or an online chat list.

Thanks!

(I guess my questions are about about the spec, but this repo seems also appropriate.)

**Comment by wincent** [comment]
> Does relay support pagination when the size of the collection is unknown? ie sometimes it is expensive to know the exact size of a collection or just needed from a product perspective. Like search results.

Yes, and the Facebook newsfeed (which you mentioned) is another good example of this kind of case. Not only is it unbounded (for most intents and purposes), but the ordering is dependent on ranking that is highly sensitive to changing inputs over time, such as new items becoming available.

For cases like this, implementing your own connection logic is probably the way to go, and the data store from which the data is coming from need not be (and probably isn't) very array-like. Given the ever-changing nature of the beast, cursors are critically important, so that you can paginate through that kind of collection in a stable way (ie. without stuff getting reordered or repeated underneath you) because the cursor contains enough information to describe the set and ordering that you're paging through.

**Comment by jnak** [comment]
Thanks for your answer. Very useful. 

That totally makes sense.

Ok then in the case of Facebook newsfeed, since the 'last' arg does not make sense by itself, how does the server handle this if a relay client ask for newsfeed(last: 10) {...} ? Is it defined by the spec? Or is it just the responsibility of the relay client (and hence the implementor) not to issue a query like this?

I guess my question could be generalized to most graphql spec extensions. Is there any way to describe in graphql that only some extension (or part of it) is supported? Any tool that exists (or may exist in the future) to verify the compliance with an extension?

Thanks!

**Comment by wincent** [comment]
Closing out some old issues, but before I do:

> Ok then in the case of Facebook newsfeed, since the 'last' arg does not make sense by itself, how does the server handle this if a relay client ask for newsfeed(last: 10) {...} ? Is it defined by the spec? 

It's not defined by the spec, and I have no idea what the server does (I can issue such a query and it dutifully returns me a set of items, but exactly how it chose them is inscrutable to me).

In general I don't think this is enforceable in the type system or the spec, but there is a tacit pact here that the server will give the client a "reasonable" for response for a "reasonable" query; if the client asks for something "unreasonable", then all bets are off.

> I guess my question could be generalized to most graphql spec extensions. Is there any way to describe in graphql that only some extension (or part of it) is supported? Any tool that exists (or may exist in the future) to verify the compliance with an extension?

Great question! If you find out about such a tool or build anything, please share it. We certainly do some custom validations on our own schema and queries, which is one way to verify that things are legit (at least within the bounds of what is expressible in the GraphQL type system).
