### ISSUE TITLE
Why is there no 'position' argument?

### ISSUE THREAD

**Issue by Secretmapper** [graphql/graphql-relay-js#83]
I guess this is as much a question to the graphql+relay spec, but I'm confused with regards to the lack of 'position' as an argument. I know that the reason it uses complicated pagination is because of unbounded and order-independent results, but I have a use case I'm not sure how to go about doing in graphql+relay (though it's quite easy so I'm sure I just missed something).

How do I, say, get the 5th item (and only 5th item), if my list is ordered (by, say, an orderBy argument).

**Comment by wincent** [comment]
Thanks for your question! I have an answer for you, but we want to make sure to keep signal strong in the GitHub issue tracker (for issues and bugs). Would you be able to post this question to Stack Overflow with the tag #relayjs? I'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by Secretmapper** [comment]
@wincent That makes sense! I've asked the question here:

https://stackoverflow.com/questions/36994711/why-is-there-no-position-argument-in-relaygraphq-connections

Thanks!

**Comment by wincent** [comment]
I see you already got a couple of answers over there, but I will add an additional comment or two there presently. Marking this one as closed for now.
