### ISSUE TITLE
nodeDefination for multiple role

### ISSUE THREAD

**Issue by ieow** [graphql/graphql-relay-js#84]
We could check rootValue or context to determine request's role permission for graphql request.
How do we check permission for nodeDefination (request thru 'node' ) ?

**Comment by wincent** [comment]
Thanks for your question! I have an answer for you — the sneak preview of which is that you have access to `context` and `rootValue` in the resolver function that you pass into `nodeDefinitions` — but we want to make sure to keep signal strong in the GitHub issue tracker (for issues and bugs). Would you be able to post this question to Stack Overflow with the tag #relayjs? I'll be happy to answer there. Post a link to your Stack Overflow question here, so that we don't lose track of it.

https://stackoverflow.com/questions/ask?tags=relayjs

**Comment by ieow** [comment]
Sorry for the delay.
I posted at stack overflow at this link
http://stackoverflow.com/questions/37106589/how-to-access-rootvalue-or-context-for-nodedefination

**Comment by wincent** [comment]
Closing this out. There is an answer on the linked Stack Overflow question.
